import { MigrationInterface, QueryRunner } from "typeorm";

export class autogenerated1666153805642 implements MigrationInterface {
    name = 'autogenerated1666153805642'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`network\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`share_id\` (\`id\` varchar(5) NOT NULL, \`sharingUser\` varchar(32) NOT NULL, \`networkId\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`share_id\` ADD CONSTRAINT \`FK_26ca8e785e461f748d210bc29b4\` FOREIGN KEY (\`networkId\`) REFERENCES \`network\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`share_id\` DROP FOREIGN KEY \`FK_26ca8e785e461f748d210bc29b4\``);
        await queryRunner.query(`DROP TABLE \`share_id\``);
        await queryRunner.query(`DROP TABLE \`network\``);
    }

}
